const productsData = [
    {
        id: 1,
        name: "AetherBook X1",
        description: "Ligera como el aire, poderosa como un servidor. Con procesadores de última generación y batería de 1",
        price: 220000,
        stock: 10,
        thumbnail: "product1.jpg",
    },
    {
        id: 2,
        name: "NovaEdge Pro",
        description: "Diseñada para la creatividad y la ingeniería. Pantalla 4K ultrabrillante, tarjeta gráfica dedicada y",
        price: 300000,
        stock: 3,
        thumbnail: "product2.jpg",
    },
    {
        id: 3,
        name: "Zenith Ultra",
        description: "La laptop premium para quienes buscan lo máximo. Chasis de aluminio, almacenamiento SSD ultrarrápido y sonido envolvente optimizado.",
        price: 350000,
        stock: 4,
        thumbnail: "product3.jpg",
    },
    {
        id: 4,
        name: "Lumina Air",
        description: "Minimalista y elegante. Su teclado retroiluminado y peso ultraligero la convierten en la compañera p",
        price: 220000,
        stock: 5,
        thumbnail: "product4.jpg",
    },
    {
        id: 5,
        name: "Quantum Flex",
        description: "La 2-en-1 que se adapta a ti. Puede transformarse en tablet, laptop o estación de trabajo. Compatibl",
        price: 300000,
        stock: 2,
        thumbnail: "product5.jpg",
    },
    {
        id: 6,
        name: "Orion Max",
        description: "Laptop todoterreno con pantalla Full HD de 16”, procesador de alto rendimiento y doble sistema de ve",
        price: 320000,
        stock: 6,
        thumbnail: "product6.jpg",
    },
    {
        id: 7,
        name: "Vortex Neo",
        description: "Potencia de gaming en un diseño elegante. Con gráficos dedicados, teclado RGB personalizable y siste",
        price: 600000,
        stock: 2,
        thumbnail: "product7.jpg",
    },
    {
        id: 8,
        name: "Atlas Core",
        description: "Construida para la productividad. Su teclado ergonómico, conectividad múltiple (HDMI, USB-C, Thunder)",
        price: 400000,
        stock: 3,
        thumbnail: "product8.jpg",
    },
    {
        id: 9,
        name: "Eclipse One",
        description: "Un diseño futurista con marco ultrafino y pantalla OLED. Incluye lector de huellas, carga rápida y t",
        price: 500000,
        stock: 7,
        thumbnail: "product9.jpg",
    },
    {
        id: 10,
        name: "Pulse Evo",
        description: "Ultraportátil, con solo 1 kg de peso y chasis de aleación reforzada. Ideal para estudiantes y creado",
        price: 300000,
        stock: 3,
        thumbnail: "product10.jpg",
    },
    {
        id: 11,
        name: "SkyTab Air",
        description: "Ultraligera y con diseño minimalista, perfecta para quienes buscan portabilidad sin perder potencia.",
        price: 100000,
        stock: 5,
        thumbnail: "product11.jpg",
    },
    {
        id: 12,
        name: "Vega Pro 12",
        description: "Con pantalla de 12” en resolución 2K, procesador de alto rendimiento y stylus incluido, es la opción",
        price: 80000,
        stock: 3,
        thumbnail: "product12.jpg",
    },
    {
        id: 13,
        name: "Lumen One",
        description: "Tablet versátil con doble altavoz estéreo y batería de larga duración. Diseñada para entretenimiento",
        price: 80000,
        stock: 8,
        thumbnail: "product13.jpg",
    },
    {
        id: 14,
        name: "Orion Pad X",
        description: "Poder de un laptop en formato tablet. Compatible con teclado magnético y multitarea avanzada, ideal ",
        price: 90000,
        stock: 7,
        thumbnail: "product14.jpg",
    },
    {
        id: 15,
        name: "Nebula X",
        description: "Diseño futurista con pantalla AMOLED de 6.7”, cámara triple de 64 MP y batería de carga rápida de 50",
        price: 100000,
        stock: 11,
        thumbnail: "product15.jpg",
    },
    {
        id: 16,
        name: "Astra One",
        description: "El equilibrio ideal entre rendimiento y precio. Con procesador de última generación, 6 GB de RAM y a",
        price: 720000,
        stock: 4,
        thumbnail: "product16.jpg",
    },
    {
        id: 17,
        name: "Lynx Pro",
        description: "Enfocado en la fotografía: cámara principal de 108 MP, estabilización óptica y modo nocturno avanzad",
        price: 200000,
        stock: 2,
        thumbnail: "product17.jpg",
    },
    {
        id: 18,
        name: "Vortex Z",
        description: "Diseñado para gamers móviles. Pantalla de 144 Hz, GPU optimizada y sistema de refrigeración líquida.",
        price: 70000,
        stock: 3,
        thumbnail: "product18.jpg",
    },
    {
        id: 19,
        name: "Eclipse Mini",
        description: "Smartphone compacto de 5.8” con gran rendimiento. Ideal para quienes prefieren un tamaño manejable s",
        price: 120000,
        stock: 5,
        thumbnail: "product19.jpg",
    },
    {
        id: 20,
        name: "Quantum Edge",
        description: "El más premium de la línea: pantalla curva de 6.9”, desbloqueo facial 3D, sonido estéreo envolvente ",
        price: 140000,
        stock: 5,
        thumbnail: "product20.jpg",
    },
];

export default productsData;